embed_assets: on
stylesheets:
  all_minified:
    - "public/stylesheets/my-style.css"
    - "public/stylesheets/post.css"
    - "public/stylesheets/superfish.css"
    - "public/stylesheets/layout/comment.css"
javascripts:
  all_minified:
    - 'public/javascripts/jquery.min.js'
    - 'public/javascripts/google.analitics.js'
    - 'public/javascripts/comments/index.js'
    - 'public/javascripts/superfish.js'
    - 'public/javascripts/twitter-button.js'
    - 'public/javascripts/plusone-button.js'
    - 'public/javascripts/scrollable-div/scrollable-div.js'
    - 'public/javascripts/scrollable-div/initializer.js'
    #- 'public/javascripts/ajax.js'
